---
global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#sergei_rogulev'
