---
version: '3.3'
services:
  post_db:
    container_name: ${COMPOSE_PROJECT_NAME}-mongo-${MONGO_TAG_VERSION}
    image: mongo:${MONGO_TAG_VERSION}
    volumes:
      - post_db:${DB_PATH}
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    # build: ./ui
    container_name: ${COMPOSE_PROJECT_NAME}-${USERNAME}-ui-${UI_TAG_VERSION}
    image: ${USERNAME}/ui:${UI_TAG_VERSION}
    ports:
      - ${UI_HOST_PORT}:${UI_CONTAINER_PORT}/tcp
    networks:
      - front_net
  post:
    # build: ./post-py
    container_name: ${COMPOSE_PROJECT_NAME}-${USERNAME}-post-${POST_TAG_VERSION}
    image: ${USERNAME}/post:${POST_TAG_VERSION}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
  comment:
    # build: ./comment
    container_name: ${COMPOSE_PROJECT_NAME}-${USERNAME}-comment-${COMMENT_TAG_VERSION}
    image: ${USERNAME}/comment:${COMMENT_TAG_VERSION}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

  mongodb-exporter:
    image: eses/mongodb_exporter:latest
    command:
      - '-mongodb.uri=mongodb://post_db:27017'
    networks:
      - back_net

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    networks:
      - front_net

volumes:
  prometheus_data:
  post_db:

networks:
  # reddit:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
